language: generic
sudo: required
services:
  - docker

# Build image that can run tests
before_install:
  - docker build -t imcool2551/react-test -f ./client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true imcool2551/react-test npm run test

after_success:
  - docker build -t imcool2551/multi-client ./client
  - docker build -t imcool2551/multi-nginx ./nginx
  - docker build -t imcool2551/multi-server ./server
  - docker build -t imcool2551/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push built docker images to docker-hub
  - docker push imcool2551/multi-client
  - docker push imcool2551/multi-nginx
  - docker push imcool2551/multi-server
  - docker push imcool2551/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-424468057789
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
